const cfg = window.CAREHUB_CONFIG;
const sb = window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY);
let state = { user:null, family:null, members:[], parent:null, meds:[], appointments:[], docs:[], notes:[], section:'dashboard', loading:true };
const $ = id => document.getElementById(id);
const app = $('app');
function toast(m){const t=$('toast');const e=document.createElement('div');e.className='toast';e.textContent=m;t.appendChild(e);setTimeout(()=>e.remove(),2600)}
function esc(s=''){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function init(){ const {data:{session}}=await sb.auth.getSession(); state.user=session?.user||null; if(state.user) await loadAll(); state.loading=false; render(); sb.auth.onAuthStateChange(async(_,session)=>{state.user=session?.user||null;if(state.user) await loadAll();render()}); }
async function loadAll(){
  const {data:fams}=await sb.from('family_members').select('role,families(*)').eq('user_id',state.user.id).limit(1);
  state.family=fams?.[0]?.families||null; state.role=fams?.[0]?.role||null;
  if(!state.family){ state.parent=null; return; }
  const fid=state.family.id;
  const [members,parent,meds,apps,docs,notes]=await Promise.all([
    sb.from('family_members').select('role,user_id,profiles(full_name,email)').eq('family_id',fid),
    sb.from('parents').select('*').eq('family_id',fid).maybeSingle(),
    sb.from('medications').select('*').eq('family_id',fid).order('created_at',{ascending:false}),
    sb.from('appointments').select('*').eq('family_id',fid).order('starts_at',{ascending:true}),
    sb.from('documents').select('*').eq('family_id',fid).order('created_at',{ascending:false}),
    sb.from('notes').select('*,profiles(full_name)').eq('family_id',fid).order('created_at',{ascending:false})
  ]);
  state.members=members.data||[]; state.parent=parent.data; state.meds=meds.data||[]; state.appointments=apps.data||[]; state.docs=docs.data||[]; state.notes=notes.data||[];
}
function canEdit(){return ['owner','admin','caregiver'].includes(state.role)} function isAdmin(){return ['owner','admin'].includes(state.role)}
async function signUp(e){e.preventDefault();const f=new FormData(e.target);const email=f.get('email'),password=f.get('password'),name=f.get('name');const {error}=await sb.auth.signUp({email,password,options:{data:{full_name:name}}}); if(error) return toast(error.message); toast('Check your email to confirm your account.');}
async function signIn(e){e.preventDefault();const f=new FormData(e.target);const {error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')}); if(error) toast(error.message)}
async function signOut(){await sb.auth.signOut(); state={...state,user:null,family:null}; render()}
async function createFamily(e){e.preventDefault();const f=new FormData(e.target);const name=f.get('family_name');const p=f.get('parent_name');const {data:family,error}=await sb.from('families').insert({name}).select().single(); if(error)return toast(error.message); await sb.from('family_members').insert({family_id:family.id,user_id:state.user.id,role:'owner'}); await sb.from('parents').insert({family_id:family.id,full_name:p,address:f.get('address'),emergency_contact:f.get('emergency')}); await loadAll(); toast('Family workspace created'); render();}
async function saveProfile(e){e.preventDefault();const f=new FormData(e.target);const row={family_id:state.family.id,full_name:f.get('full_name'),age:f.get('age'),address:f.get('address'),emergency_contact:f.get('emergency_contact'),doctor:f.get('doctor'),pharmacy:f.get('pharmacy'),allergies:f.get('allergies'),care_preferences:f.get('care_preferences')}; const q=state.parent?.id?sb.from('parents').update(row).eq('id',state.parent.id):sb.from('parents').insert(row); const {error}=await q; if(error)return toast(error.message); await loadAll(); toast('Profile saved'); render();}
async function addMedication(e){e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from('medications').insert({family_id:state.family.id,name:f.get('name'),dosage:f.get('dosage'),frequency:f.get('frequency'),time_of_day:f.get('time_of_day'),refill_date:f.get('refill_date')||null,notes:f.get('notes')}); if(error)return toast(error.message); await loadAll(); toast('Medication added'); render();}
async function addAppointment(e){e.preventDefault();const f=new FormData(e.target);const starts=`${f.get('date')}T${f.get('time')||'09:00'}`;const {error}=await sb.from('appointments').insert({family_id:state.family.id,title:f.get('title'),starts_at:starts,location:f.get('location'),responsible:f.get('responsible'),notes:f.get('notes'),remind_by_email:!!f.get('email'),remind_by_sms:!!f.get('sms')}); if(error)return toast(error.message); await loadAll(); toast('Appointment added'); render();}
async function addNote(e){e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from('notes').insert({family_id:state.family.id,author_id:state.user.id,body:f.get('body')}); if(error)return toast(error.message); await loadAll(); toast('Family note posted'); render();}
async function inviteMember(e){e.preventDefault();const f=new FormData(e.target);const token=crypto.randomUUID();const {error}=await sb.from('invitations').insert({family_id:state.family.id,email:f.get('email'),role:f.get('role'),token,invited_by:state.user.id}); if(error)return toast(error.message); toast('Invite created. Send this link: '+cfg.APP_URL+'?invite='+token)}
async function acceptInvite(token){const {data:inv,error}=await sb.from('invitations').select('*').eq('token',token).is('accepted_at',null).single(); if(error||!inv)return toast('Invalid or expired invite'); await sb.from('family_members').insert({family_id:inv.family_id,user_id:state.user.id,role:inv.role}); await sb.from('invitations').update({accepted_at:new Date().toISOString()}).eq('id',inv.id); await loadAll(); toast('Invitation accepted'); history.replaceState(null,'',location.pathname); render();}
async function remove(id,table){if(!confirm('Delete this item?'))return;const {error}=await sb.from(table).delete().eq('id',id); if(error)return toast(error.message); await loadAll(); render();}
async function getKey(){const k='carehub_family_key_'+state.family.id; let raw=localStorage.getItem(k); if(!raw){const bytes=crypto.getRandomValues(new Uint8Array(32)); raw=btoa(String.fromCharCode(...bytes)); localStorage.setItem(k,raw); alert('A browser encryption key was created. For a production app, move this to a secure family key-sharing flow.');} const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0)); return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt']);}
async function uploadDocument(e){e.preventDefault();const f=new FormData(e.target);const file=f.get('file'); if(!file?.size)return toast('Choose a file'); const key=await getKey(); const iv=crypto.getRandomValues(new Uint8Array(12)); const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,await file.arrayBuffer()); const path=`${state.family.id}/${crypto.randomUUID()}-${file.name}.encrypted`; const up=await sb.storage.from('care-documents').upload(path,new Blob([encrypted]),{contentType:'application/octet-stream'}); if(up.error)return toast(up.error.message); const {error}=await sb.from('documents').insert({family_id:state.family.id,title:f.get('title')||file.name,document_type:f.get('type'),file_path:path,original_filename:file.name,iv:btoa(String.fromCharCode(...iv)),notes:f.get('notes')}); if(error)return toast(error.message); await loadAll(); toast('Encrypted document uploaded'); render();}
async function checkout(){const {data,error}=await sb.functions.invoke('create-checkout-session',{body:{priceId:cfg.STRIPE_PRICE_ID,familyId:state.family.id,returnUrl:location.href}}); if(error)return toast(error.message); location.href=data.url;}
function setSection(s){state.section=s;render()} function dt(x){return x?new Date(x).toLocaleString([], {dateStyle:'medium', timeStyle:'short'}):'TBD'}
function authView(){return `<div class="auth-wrap"><div class="auth-card"><section class="auth-hero"><div class="logo"><div class="logo-mark">C</div><div><h2>CareHub</h2><p>Secure family care coordination</p></div></div><h1>One calm place to manage a parent&apos;s care.</h1><p class="subtitle">Now wired for Supabase auth, PostgreSQL data, encrypted file uploads, roles, invitations, reminder hooks, and Stripe subscriptions.</p><div class="notice">Set your Supabase URL and anon key in <b>config.js</b> before deploying.</div></section><section class="auth-panel"><h2>Sign in</h2><form class="form" onsubmit="signIn(event)"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="primary">Sign in</button></form><hr><h2>Create account</h2><form class="form" onsubmit="signUp(event)"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="8" required></div><button class="secondary">Create account</button></form></section></div></div>`}
function setupView(){const token=new URLSearchParams(location.search).get('invite');return shell(`<div class="card"><h2>${token?'Accept family invitation':'Create your family workspace'}</h2>${token?`<p class="subtitle">Join the care team attached to this invitation.</p><button class="primary" onclick="acceptInvite('${esc(token)}')">Accept invitation</button>`:`<form class="form" onsubmit="createFamily(event)"><div class="field"><label>Family workspace name</label><input name="family_name" placeholder="Wilson Family Care" required></div><div class="field"><label>Parent name</label><input name="parent_name" placeholder="Margaret Wilson" required></div><div class="field"><label>Address</label><input name="address"></div><div class="field"><label>Emergency contact</label><input name="emergency"></div><button class="primary">Create workspace</button></form>`}</div>`)}
function shell(content){const nav=[['dashboard','Dashboard','🏠'],['profile','Parent Profile','👤'],['meds','Medications','💊'],['calendar','Calendar','📅'],['documents','Documents','🔒'],['notes','Family Notes','💬'],['team','Team & Billing','👥']];return `<div class="app-shell"><aside class="sidebar"><div class="logo"><div class="logo-mark">C</div><div><h2>CareHub</h2><p>${esc(state.family?.name||'Secure MVP')}</p></div></div><div class="care-card"><strong>${esc(state.parent?.full_name||'No parent yet')}</strong><span>${esc(state.parent?.address||'Add profile details')}<br>Role: ${esc(state.role||'none')}</span></div><nav class="nav">${nav.map(n=>`<button class="${state.section===n[0]?'active':''}" onclick="setSection('${n[0]}')"><span>${n[2]} ${n[1]}</span><span>›</span></button>`).join('')}</nav><p class="footer">Secure MVP: Supabase + PostgreSQL + RLS + encrypted uploads.</p></aside><main class="workspace"><div class="mobile-bar"><div class="logo"><div class="logo-mark">C</div><div><h2>CareHub</h2></div></div><select onchange="setSection(this.value)">${nav.map(n=>`<option value="${n[0]}" ${state.section===n[0]?'selected':''}>${n[1]}</option>`).join('')}</select></div>${content}<p class="footer">Do not store live regulated medical data until legal/security review is complete.</p></main></div>`}
function header(t,s,a=''){return `<div class="topbar"><div><p class="eyebrow">CareHub Secure MVP</p><h2>${t}</h2><p class="subtitle">${s}</p></div><div class="actions">${a}<button class="secondary" onclick="signOut()">Sign out</button></div></div>`}
function dashboard(){return header(`Today for ${esc(state.parent?.full_name||'your parent')}`,'Shared snapshot for the whole care team.',`<button class="primary" onclick="checkout()">Upgrade with Stripe</button>`)+`<div class="grid three"><div class="card stat"><div><span class="pill">Active</span><h3>Medications</h3></div><div class="stat-number">${state.meds.length}</div></div><div class="card stat"><div><span class="pill green">Upcoming</span><h3>Care events</h3></div><div class="stat-number">${state.appointments.length}</div></div><div class="card stat"><div><span class="pill orange">Secure</span><h3>Documents</h3></div><div class="stat-number">${state.docs.length}</div></div></div><div class="grid two" style="margin-top:18px"><div class="card"><div class="section-title"><h3>Upcoming appointments</h3><span class="pill green">Reminders enabled</span></div><div class="list">${state.appointments.slice(0,4).map(a=>`<div class="item"><strong>${esc(a.title)}</strong><p>${dt(a.starts_at)} • ${esc(a.location||'No location')}</p><p>Responsible: ${esc(a.responsible||'Unassigned')}</p></div>`).join('')||'<div class="empty">Add the first appointment.</div>'}</div></div><div class="card"><div class="section-title"><h3>Latest family notes</h3><button class="secondary" onclick="setSection('notes')">Post update</button></div><div class="list">${state.notes.slice(0,4).map(n=>`<div class="item"><strong>${esc(n.profiles?.full_name||'Family member')}</strong><p>${esc(n.body)}</p></div>`).join('')||'<div class="empty">No notes yet.</div>'}</div></div></div>`}
function profile(){const p=state.parent||{};return header('Parent Profile','Emergency contacts, doctors, pharmacy, allergies, and care preferences.')+`<div class="card"><form class="form" onsubmit="saveProfile(event)">${['full_name','age','address','emergency_contact','doctor','pharmacy','allergies','care_preferences'].map(k=>`<div class="field"><label>${k.replaceAll('_',' ')}</label><input name="${k}" value="${esc(p[k]||'')}" ${!canEdit()?'disabled':''}></div>`).join('')}<button class="primary" ${!canEdit()?'disabled':''}>Save profile</button></form></div>`}
function meds(){return header('Medication Tracker','Manual medication list and refill notes.')+`<div class="grid two"><div class="card"><h3>Add medication</h3><form class="form" onsubmit="addMedication(event)">${['name','dosage','frequency','time_of_day','refill_date','notes'].map(k=>`<div class="field"><label>${k.replaceAll('_',' ')}</label><input name="${k}" ${k==='refill_date'?'type="date"':''} required=${k==='name'}></div>`).join('')}<button class="primary">Add</button></form></div><div class="card"><h3>Current meds</h3><div class="list">${state.meds.map(m=>`<div class="item"><div class="item-head"><div><strong>${esc(m.name)} — ${esc(m.dosage)}</strong><p>${esc(m.frequency)} ${esc(m.time_of_day||'')}</p><p>Refill: ${esc(m.refill_date||'not set')}</p></div>${canEdit()?`<button class="danger" onclick="remove('${m.id}','medications')">Delete</button>`:''}</div></div>`).join('')||'<div class="empty">No medications yet.</div>'}</div></div></div>`}
function calendar(){return header('Appointment Calendar','Doctor visits, caregiver schedules, transportation, and email/SMS reminder flags.')+`<div class="grid two"><div class="card"><h3>Add appointment</h3><form class="form" onsubmit="addAppointment(event)"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Date</label><input name="date" type="date" required></div><div class="field"><label>Time</label><input name="time" type="time"></div><div class="field"><label>Location</label><input name="location"></div><div class="field"><label>Responsible</label><input name="responsible"></div><div class="field"><label>Notes</label><textarea name="notes"></textarea></div><label><input type="checkbox" name="email"> Email reminder</label><label><input type="checkbox" name="sms"> SMS reminder</label><button class="primary">Schedule</button></form></div><div class="card"><h3>Events</h3><div class="list">${state.appointments.map(a=>`<div class="item"><div class="item-head"><div><strong>${esc(a.title)}</strong><p>${dt(a.starts_at)} • ${esc(a.location||'')}</p><p>${esc(a.notes||'')}</p></div>${canEdit()?`<button class="danger" onclick="remove('${a.id}','appointments')">Delete</button>`:''}</div></div>`).join('')||'<div class="empty">No events yet.</div>'}</div></div></div>`}
function documents(){return header('Encrypted Document Vault','Files are encrypted in the browser before upload to Supabase Storage.')+`<div class="notice">MVP encryption uses a browser-held family key. Production should add audited key recovery and secure sharing.</div><div class="grid two" style="margin-top:18px"><div class="card"><h3>Upload encrypted file</h3><form class="form" onsubmit="uploadDocument(event)"><div class="field"><label>Title</label><input name="title"></div><div class="field"><label>Type</label><select name="type"><option>Insurance</option><option>Legal</option><option>Medical Record</option><option>Care Plan</option></select></div><div class="field"><label>File</label><input name="file" type="file" required></div><div class="field"><label>Notes</label><textarea name="notes"></textarea></div><button class="primary">Encrypt & upload</button></form></div><div class="card"><h3>Documents</h3><div class="list">${state.docs.map(d=>`<div class="item"><strong>🔒 ${esc(d.title)}</strong><p>${esc(d.document_type||'Document')} • ${esc(d.original_filename||'encrypted file')}</p><p>${esc(d.notes||'')}</p></div>`).join('')||'<div class="empty">No encrypted documents yet.</div>'}</div></div></div>`}
function notes(){return header('Shared Family Notes','Updates visible to all permitted family members and caregivers.')+`<div class="grid two"><div class="card"><h3>Post update</h3><form class="form" onsubmit="addNote(event)"><div class="field"><label>Update</label><textarea name="body" rows="5" required></textarea></div><button class="primary">Post note</button></form></div><div class="card"><h3>Family feed</h3><div class="list">${state.notes.map(n=>`<div class="item"><strong>${esc(n.profiles?.full_name||'Family member')}</strong><p>${esc(n.body)}</p></div>`).join('')||'<div class="empty">No notes yet.</div>'}</div></div></div>`}
function team(){return header('Team, Permissions & Billing','Invite caregivers, assign roles, and manage subscription checkout.',`<button class="primary" onclick="checkout()">Start subscription</button>`)+`<div class="grid two"><div class="card"><h3>Invite family member</h3>${isAdmin()?`<form class="form" onsubmit="inviteMember(event)"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Role</label><select name="role"><option value="admin">Admin</option><option value="caregiver">Caregiver</option><option value="viewer">Viewer</option></select></div><button class="primary">Create invite link</button></form>`:'<div class="empty">Only owners/admins can invite members.</div>'}<p class="subtitle"><b>Roles:</b> owner/admin manage billing and invites; caregiver edits care info; viewer can read only.</p></div><div class="card"><h3>Care team</h3><div class="list">${state.members.map(m=>`<div class="item"><strong>${esc(m.profiles?.full_name||m.user_id)}</strong><p>${esc(m.profiles?.email||'')} • ${esc(m.role)}</p></div>`).join('')}</div></div></div>`}
function render(){if(state.loading)return app.innerHTML='<div class="auth-wrap"><div class="card">Loading...</div></div>'; if(!state.user)return app.innerHTML=authView(); if(!state.family)return app.innerHTML=setupView(); const views={dashboard,profile,meds,calendar,documents,notes,team}; app.innerHTML=shell((views[state.section]||dashboard)());}
init();
